name: Java CI with MySQL

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: inventory_db
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Wait for MySQL to be ready
        run: |
          for i in `seq 1 30`; do
            if echo 'SELECT 1' | mysql -h 127.0.0.1 -u testuser -ptestpass testdb &> /dev/null; then
              echo "MySQL is up and running"
              break
            fi
            echo "Waiting for MySQL to be ready... ($i/30)"
            sleep 2
          done

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run tests with Maven
        run: mvn test --no-transfer-progress