name: Java CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: inventory_db
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17
      - name: Build and Test
        run: mvn clean test --no-transfer-progress